# Generated by Django 5.0.6 on 2024-05-27 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gltf_plus_image',
            name='height',
            field=models.IntegerField(blank=True, editable=False, verbose_name='height'),
        ),
        migrations.AlterField(
            model_name='gltf_plus_image',
            name='width',
            field=models.IntegerField(blank=True, editable=False, verbose_name='width'),
        ),
    ]
