# Generated by Django 5.0.6 on 2024-05-27 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_gltf_plus_image_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gltf_plus_image',
            name='height',
            field=models.IntegerField(default=1024, editable=False, verbose_name='height'),
        ),
        migrations.AlterField(
            model_name='gltf_plus_image',
            name='width',
            field=models.IntegerField(default=1024, editable=False, verbose_name='width'),
        ),
    ]
